version: '3'
services:
  web:
    build: .
      
    ports:
      # - '7000:8000'
      - "8000:8000"
    volumes:
      - ./app:/app
    command: 'python manage.py runserver 0.0.0:8000' 
    # command: 'npm run build'
    image: password-manager_web