version: '3'
services:
  web:
    build: 
      context: .
    ports:
      - '7000:8000'
    volumes:
      - ./app:/app
    command: 'python manage.py runserver 0.0.0.0:8000'
    image: password-manager_web