# Generated by Django 4.0.4 on 2022-06-30 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_registration_password_alter_registration_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createmp',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
