# Generated by Django 4.0.4 on 2022-09-25 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2022, 9, 25, 13, 15, 21, 593344, tzinfo=utc), max_length=200, null=True),
        ),
    ]
