# Generated by Django 4.0.4 on 2022-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_createmp_remove_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='media/default/default.jpg', upload_to='media/images'),
        ),
    ]
