# Generated by Django 4.1.4 on 2022-12-17 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2022, 12, 17, 5, 58, 32, 678302, tzinfo=datetime.timezone.utc), max_length=200, null=True),
        ),
    ]
